CREATE TABLE "users" (
  "id" bigint PRIMARY KEY,
  "firstname" varchar,
  "lastname" varchar,
  "email" email,
  "username" varchar,
  "password" varchar,
  "created_at" timestamp
);

CREATE TABLE "recipes" (
  "id" bigint PRIMARY KEY,
  "user_id" int,
  "title" varchar,
  "description" varchar,
  "created_at" timestamp,
  "image_url" varchar
);


CREATE TABLE recipe_steps (
  id bigserial PRIMARY KEY,
  recipe_id bigint REFERENCES recipes(id) ON DELETE CASCADE,
  step_number int NOT NULL,
  instruction text NOT NULL,
  UNIQUE (recipe_id, step_number)
);

CREATE TABLE ingredients (
  id bigserial PRIMARY KEY,
  recipe_id bigint REFERENCES recipes(id) ON DELETE CASCADE,
  position int NOT NULL,
  ingredient_name text NOT NULL,
  UNIQUE (recipe_id, position)
);


ALTER TABLE "recipes" ADD CONSTRAINT "user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id");

alter table users alter column id add generated by default as identity;

alter table recipes alter column id add generated by default as identity;

alter table users alter column created_at set default CURRENT_TIMESTAMP;

alter table recipes alter column created_at set default CURRENT_TIMESTAMP;

